### ISSUE TITLE
stage is stuck forever if targeted 0 clusters

### ISSUE THREAD

**Issue by riuvshyn** [Skyscanner/applicationset-progressive-sync#146]
when there are 4 stages
- stg canary
- stg other clusters
- prod canary
- prod other clusters

but there are only `1` cluster for stg and `1` for prod second stage is going into `Progressing` phase and stuck there forever.

I guess expected behaviour would be skip stage if it did not found other clusters or at least have this as an optional flag. 

ProgressiveSync object ex:
```
apiVersion: argoproj.skyscanner.net/v1alpha1
kind: ProgressiveSync
metadata:
  labels:
    argocd.argoproj.io/instance: argocd-apps
  name: test
  namespace: argocd
spec:
  sourceRef:
    apiGroup: argoproj.io/v1alpha1
    kind: ApplicationSet
    name: test
  stages:
  - maxParallel: 1
    maxTargets: 1
    name: canary rollout staging
    targets:
      clusters:
        selector:
          matchLabels:
            environment: staging
  - maxParallel: 1
    maxTargets: 100%
    name: finish rollout staging
    targets:
      clusters:
        selector:
          matchLabels:
            environment: staging
  - maxParallel: 1
    maxTargets: 1
    name: canary rollout production
    targets:
      clusters:
        selector:
          matchLabels:
            environment: production
  - maxParallel: 1
    maxTargets: 100%
    name: finish rollout production
    targets:
      clusters:
        selector:
          matchLabels:
            environment: production
status:
  conditions:
  - lastTransitionTime: "2021-12-09T10:50:24Z"
    message: finish rollout staging stage in progress
    reason: StagesProgressing
    status: "False"
    type: Completed
  stages:
  - finishedAt: "2021-12-09T14:34:42Z"
    message: canary rollout staging stage completed
    name: canary rollout staging
    phase: Succeeded
  - message: finish rollout staging stage in progress
    name: finish rollout staging
    phase: Progressing
    startedAt: "2021-12-09T14:34:42Z"
  - finishedAt: "2021-12-09T12:16:43Z"
    message: canary rollout production stage completed
    name: canary rollout production
    phase: Succeeded
  - finishedAt: "2021-12-09T12:13:50Z"
    message: finish rollout production stage completed
    name: finish rollout production
    phase: Succeeded
```

**Comment by maruina** [comment]
Fixed in https://github.com/Skyscanner/applicationset-progressive-sync/pull/143 and a new test covering this at https://github.com/Skyscanner/applicationset-progressive-sync/blob/1685ca78cabf64df1a5b9f1f6a6eedb0acf7df78/controllers/progressivesync_controller_test.go#L247

**Comment by riuvshyn** [comment]
I've recently tested 0.6.0 and confirm that this issues is gone now 👍🏽

**Comment by riuvshyn** [comment]
hello @maruina I had to re-open this ticket as I believe the issue is still there. I was able to reproduce it with following configuration:
we have `only 1` cluster registered in argocd labeled as `environment: production`

progressive sync object looks like this:
```
apiVersion: argoproj.skyscanner.net/v1alpha1
kind: ProgressiveSync
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    argocd.argoproj.io/instance: argocd-apps
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  appSetRef:
    name: aws-load-balancer-controller
  stages:
  - maxParallel: 1
    maxTargets: 1
    name: canary rollout staging
    targets:
      clusters:
        selector:
          matchLabels:
            environment: staging
  - maxParallel: 2
    maxTargets: 99999
    name: finish rollout staging
    targets:
      clusters:
        selector:
          matchLabels:
            environment: staging
  - maxParallel: 1
    maxTargets: 1
    name: canary rollout production
    targets:
      clusters:
        selector:
          matchLabels:
            environment: production
  - maxParallel: 2
    maxTargets: 99999
    name: finish rollout production
    targets:
      clusters:
        selector:
          matchLabels:
            environment: production
status:
  conditions:
  - lastTransitionTime: "2022-02-03T12:14:52Z"
    message: Reconciliation in progress
    reason: Progressing
    status: Unknown
    type: Ready
  lastSyncedStage: canary rollout staging
  lastSyncedStageStatus: StageProgressing
  observedGeneration: 1
```

progressive sync logs:
```
2022-02-03T12:14:52.886Z	INFO	controller-runtime.manager.controller.progressivesync	progressive sync started	{"reconciler group": "argoproj.skyscanner.net", "reconciler kind": "ProgressiveSync", "name": "aws-load-balancer-controller", "namespace": "argocd"}
2022-02-03T12:14:52.886Z	INFO	controller-runtime.manager.controller.progressivesync	stage reconciled	{"reconciler group": "argoproj.skyscanner.net", "reconciler kind": "ProgressiveSync", "name": "aws-load-balancer-controller", "namespace": "argocd", "stage": "canary rollout staging", "status": "StageProgressing"}
2022-02-03T12:14:52.967Z	INFO	controller-runtime.manager.controller.progressivesync	progressive sync started	{"reconciler group": "argoproj.skyscanner.net", "reconciler kind": "ProgressiveSync", "name": "aws-load-balancer-controller", "namespace": "argocd"}
2022-02-03T12:14:52.968Z	INFO	controller-runtime.manager.controller.progressivesync	stage reconciled	{"reconciler group": "argoproj.skyscanner.net", "reconciler kind": "ProgressiveSync", "name": "aws-load-balancer-controller", "namespace": "argocd", "stage": "canary rollout staging", "status": "StageProgressing"}
```

so it is stuck on first stage `name: canary rollout staging` with status:
```
status:
  conditions:
  - lastTransitionTime: "2022-02-03T12:14:52Z"
    message: Reconciliation in progress
    reason: Progressing
    status: Unknown
    type: Ready
  lastSyncedStage: canary rollout staging
  lastSyncedStageStatus: StageProgressing
  observedGeneration: 1
```

there are no clusters yet known by argo tagged with `environment: staging` and our expectation is that controller should skip stage if no clusters were targeted for that stage.

**Comment by maruina** [comment]
Hey, thank you very much for all the details. Hopefully, I will be able to reproduce the issue in a test and then a fix.

I should start working on this in the next couple of days.

**Comment by maruina** [comment]
Fixed in #159
